add 2-column menu
hexlet-basics/hexlet-basics pull request #324
Opened 2022-11-14 20:14 UTC by fey

2 столбцовое меню, Один кастомный класс для ширины.

closes #316 
![image](https://user-images.githubusercontent.com/697178/201755884-2cb23a81-8ecf-468b-b82e-0a4f2f068432.png)

![image](https://user-images.githubusercontent.com/697178/201755959-93091fe0-b52e-4c34-ad58-5458e0d2b692.png)

![image](https://user-images.githubusercontent.com/697178/201756518-470307cd-dfb5-45ee-90dd-751897c7f883.png)

2022-11-14 20:24 UTC, fey commented
хм, из ишшуса прочитал, что див в списке - херня. 
Правлю.

2022-11-16 07:03 UTC, amshkv commented on app/views/layouts/shared/_nav.html.slim
> +          li.row
Коля, а зачем тебе тут список из двух элементов? может тогда просто уберем `ul li` чтобы нам оно не мешало и всё? да, немного потеряем в семантике, но всё же кажется это будет лучше чем так

2022-11-16 07:16 UTC, fey commented on app/views/layouts/shared/_nav.html.slim
> +          li.row
Ага, уберу. У меня были вопросы, должен ли у нас обязательно список там быть, в последний момент решил добавить его.

2022-11-16 17:35 UTC, fey commented
Актуальные скриншоты

<details>
<summary>Click me</summary>
![image](https://user-images.githubusercontent.com/697178/202252376-6aff7eb4-63d4-4109-a5d0-cac5f6f08144.png)
![image](https://user-images.githubusercontent.com/697178/202252468-a39edc59-66ba-46a8-8670-0ae18901c17c.png)
![image](https://user-images.githubusercontent.com/697178/202252526-b4914b37-b8c3-41c0-b808-ead7648247fd.png)
![image](https://user-images.githubusercontent.com/697178/202252623-efd88c92-ec99-478e-94be-57d930c5ef5c.png)

</details>

2022-11-16 17:44 UTC, fey commented on app/views/layouts/shared/_nav.html.slim
> +          li.row
Исправил.

2022-11-16 17:44 UTC, fey commented
![image](https://user-images.githubusercontent.com/697178/202254437-333cc5ed-11de-437e-b32c-0b9bcf02eba6.png)

2022-11-18 18:51 UTC, corsicanec82 commented on app/controllers/web/application_controller.rb
> +    languages_groups_by_completed = language_version_infos.each_with_object({ completed: [], in_development: [] }) do |info, acc|
Тут можно избавится от рукопашки и дополнить основной запрос в БД language_version_infos доп выборками .merge(Language.with_progress(:completed)) и .merge(Language.with_progress(:completed)), предварительно оформив их в скоупы модели info.

2022-11-27 14:29 UTC, fey commented
Новые скрины
![image](https://user-images.githubusercontent.com/697178/204140592-94b39b18-8d89-4d00-9c94-4786dfd59c9c.png)
![image](https://user-images.githubusercontent.com/697178/204140610-797ae72a-a4d3-43ba-8fc1-5aeef77554e6.png)

2022-11-27 14:32 UTC, fey commented on app/controllers/web/application_controller.rb
> +    group.in_groups(columns_count).map(&:compact).reject(&:empty?)
Поправил.

2022-11-27 14:32 UTC, fey commented on app/controllers/web/application_controller.rb
> +    columns_count = language_version_infos.size < 10 ? 1 : 2
Вынес в переменную

2022-11-27 14:32 UTC, fey commented on app/controllers/web/application_controller.rb
> +    languages_groups_by_completed = language_version_infos.each_with_object({ completed: [], in_development: [] }) do |info, acc|
Сделал со скоупом.

2022-12-06 09:01 UTC, corsicanec82 reviewed
А так в целом всё ок

2022-12-08 14:33 UTC, fey commented on app/controllers/web/application_controller.rb
> +    languages_count = completed_language_version_infos.size + incompleted_language_version_infos.size
исправил.

2022-12-08 14:34 UTC, fey commented on app/controllers/web/application_controller.rb
> +    completed_language_version_infos = Language::Version::Info
исправил.

2022-12-09 10:01 UTC, fey commented
![image](https://user-images.githubusercontent.com/697178/206676451-ba755a9d-2cd2-4b2c-afa5-dc2f21a74d02.png)

Текущий вид для 1 колонки

2022-12-09 10:02 UTC, corsicanec82 approved these changes
Выглядит всё хорошо.
@amshkv если по верстке вопросов нет, то можно принимать

2022-12-09 12:35 UTC, amshkv requested changes
<img width="286" alt="image" src="https://user-images.githubusercontent.com/23584933/206703478-7132a1e8-fcdb-4ac9-9647-7170cb5dadc4.png">
Видно что внутри языков пропало выравнивание между картинкой и названием

колонки не сбаллансированы, я бы тогда сделал через `row > col`, всё равно дивов наделал

про any(&:any?) хз, как-то сложно

поправь верстку, по коду я бы еще Кирилла спросил

2022-12-09 12:35 UTC, amshkv commented on app/views/layouts/shared/_language_menu.slim
> +- if @language_menu_data[:incompleted].any?(&:any?)
вот это вообще какая-то мегасложная конструкция :D

2022-12-09 12:35 UTC, amshkv commented on app/views/layouts/shared/_language_menu.slim
> +  / FIXME: стоит ли спользовать partial?
это не fixme

2022-12-09 12:35 UTC, amshkv commented on app/views/layouts/shared/_language_menu.slim
> +  / FIXME: стоит ли спользовать partial?
пока и так норм, чего паршалы плодить

2022-12-10 13:23 UTC, fey commented
>колонки не сбаллансированы, я бы тогда сделал через row > col, всё равно дивов наделал

можешь показать пример, как будет выглядеть верстка? Потому что я сперва так и делал, но делал это через кастомный класс, с которым все плохо выглядело на мобиле

![image](https://user-images.githubusercontent.com/697178/206857386-c7fe5df7-2acc-4ff1-a024-f486155982d1.png)

2022-12-11 06:06 UTC, fey commented
![image](https://user-images.githubusercontent.com/697178/206888851-508dcf20-61ed-4bdc-8ab6-760902ab217a.png)
![image](https://user-images.githubusercontent.com/697178/206888864-4d84ace7-fa49-4c39-a57f-a2972c93d0c3.png)
![image](https://user-images.githubusercontent.com/697178/206888881-5917565b-6867-44c7-9318-470f2394c93a.png)

2022-12-11 06:07 UTC, fey commented on app/views/layouts/shared/_language_menu.slim
> +- if @language_menu_data[:incompleted].any?(&:any?)
убрал, теперь группы не нужны

2022-12-11 06:07 UTC, fey commented on app/views/layouts/shared/_language_menu.slim
> +  / FIXME: стоит ли спользовать partial?
убрал

2022-12-11 06:14 UTC, fey commented
@amshkv к ревью готово

2022-12-11 15:19 UTC, amshkv approved these changes

2022-12-13 12:34 UTC, merged