add google one tapauth
hexlet-basics/hexlet-basics pull request #350
Opened 2022-12-27 21:02 UTC by usernaimandrey

2022-12-27 21:08 UTC, usernaimandrey commented
![Снимок экрана от 2022-12-27 23-58-02](https://user-images.githubusercontent.com/48034349/209722160-67eb496b-2813-473a-b9ba-f12d3f345e60.png)
Добавил таб google пока только на главную страницу, подскажите надо ли еще на другие добавить
Еще не очень разобрался как написать тесты на этот контроллер, по этому протестировал только руками если подскажите буду признателен

2022-12-29 12:00 UTC, grozwalker requested changes

2022-12-29 12:00 UTC, grozwalker commented on test/controllers/web/google_auth_controller_test.rb
> +class Web::GoogleAuthControllerTest < ActionDispatch::IntegrationTest
Вот косяк с тестом, никак вообще не проверяется коллбэк и что пользователь создается. Логика такая, что надо подменить метод verify_oidc, чтобы он вернул заранее известные данные и написать тест вроде:
```
    headers = { 'Cookie' => 'g_csrf_token=g_csrf_token_test;' }
    params = {
      g_csrf_token: 'g_csrf_token_test',
    }

    email = 'onetap@test.io'

    open_session do |s|
      s.post s.auth_google_onetap_callback_url, params: params, headers: headers
      s.assert_response :redirect
    end

    user = User.find_by! email: email

    assert { user.active? }
```

Внутри метода verify_oidc будет возвращаться почта  'onetap@test.io' и тест пройдет. Но у нас нет пакета для внедрения зависмостей, можно решить двумя способами
1. Застабить метод, типа такого: https://semaphoreci.com/community/tutorials/mocking-in-ruby-with-minitest
2. В сервисе при инициилизации объекта передавать класс, тогда в тесте можно его легко подменить
3. все-таки добавить пакет dry_auto-injection и использовтаь его

Мне кажется второй вариант самый простой и правильный

2022-12-29 12:00 UTC, grozwalker commented on test/controllers/web/google_auth_controller_test.rb
> +class Web::GoogleAuthControllerTest < ActionDispatch::IntegrationTest
@mokevnin подскажи, как лучше здесь протестировать?

2022-12-29 17:37 UTC, usernaimandrey commented on test/controllers/web/google_auth_controller_test.rb
> +class Web::GoogleAuthControllerTest < ActionDispatch::IntegrationTest
> Вот косяк с тестом, никак вообще не проверяется коллбэк и что пользователь создается. Логика такая, что надо подменить метод verify_oidc, чтобы он вернул заранее известные данные и написать тест вроде:
> 
> ```
>     headers = { 'Cookie' => 'g_csrf_token=g_csrf_token_test;' }
>     params = {
>       g_csrf_token: 'g_csrf_token_test',
>     }
> 
>     email = 'onetap@test.io'
> 
>     open_session do |s|
>       s.post s.auth_google_onetap_callback_url, params: params, headers: headers
>       s.assert_response :redirect
>     end
> 
>     user = User.find_by! email: email
> 
>     assert { user.active? }
> ```
> 
> Внутри метода verify_oidc будет возвращаться почта '[onetap@test.io](mailto:onetap@test.io)' и тест пройдет. Но у нас нет пакета для внедрения зависмостей, можно решить двумя способами
> 
> 1. Застабить метод, типа такого: https://semaphoreci.com/community/tutorials/mocking-in-ruby-with-minitest
> 2. В сервисе при инициилизации объекта передавать класс, тогда в тесте можно его легко подменить
> 3. все-таки добавить пакет dry_auto-injection и использовтаь его
> 
> Мне кажется второй вариант самый простой и правильный

@grozwalker на самом деле на проекте же есть и dry-container и auto-injection
https://github.com/hexlet-basics/hexlet-basics/blob/main/Gemfile#L93
на 4 проекте по рельсе и без auto-injecta обходился, просто доставал нужный обьект по ключу
https://github.com/usernaimandrey/rails-project-66/blob/main/app/services/update_repository_service.rb#L9
я просто думал что у этого гема(google-auth) есть метод как у omniauth-github что бы в тестах это за стабить.
Тогда раз есть dry-conteiner и auto-injection могу сделать через него?

2022-12-29 17:46 UTC, usernaimandrey commented on app/controllers/web/google_auth_controller.rb
> +    if user.persisted?
> Не очень понимаю как вот здесь может быть false. По идее метод сервиса просто упадет, но вижу везде такое в коде, пока оставим

на самом деле да, имеет смысл это проверять только если убрать метод с шебангом при сохранении user.save!, такая же логика в auth_controller

2023-01-01 23:50 UTC, usernaimandrey commented on test/controllers/web/google_auth_controller_test.rb
> +class Web::GoogleAuthControllerTest < ActionDispatch::IntegrationTest
@grozwalker добавил тест и стабовый класс

2023-01-10 15:23 UTC, grozwalker approved these changes
Спасибо большое!)

2023-01-10 15:23 UTC, merged

2023-01-10 18:53 UTC, usernaimandrey commented
> Спасибо большое!)

Всегда пожалуста!)